spring:
  application:
    name: chair-shop-eureka-server
server:
  port: 9000
eureka:
  server:
    enable-self-preservation: true
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
    appname: ${spring.application.name}
    #主机名称，需要在 /etc/hosts 中配置
    hostname: ${spring.application.name}
    #表示将自己的IP注册到Eureka Server。如果不配置会将操作系统的hostname到Eureka Server
    prefer-ip-address: true
    #续约任务的调用间隔时间，默认30s
    lease-renewal-interval-in-seconds: 30
    #服务失效的时间，默认90s
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/